### ISSUE TITLE
Pick `@JsonCreator` for Serde and `@Creator` for Data

### ISSUE THREAD

**Issue by soberich** [micronaut-projects/micronaut-serialization#146]
### Feature description

A pojo is constructed assymetrically.
```java
@Entity
class Pojo {

    @TypeDef(type = JSON) // saved in PG as jsonb
    NavigableMap<String, Double> valuesByKeys;

    @Creator // this should be picked coming from DB
    Pojo(NavigableMap<String, Double> valuesByKeys) {
        this.valuesByKeys = valuesByKeys;
    }

    @JsonCreator // this should be picked coming from Serde
    Pojo(Collection<String> keys, Collection<Double> values) {
        //...zip keys a and values
        // var zipped = (keys + values)
        this.valuesByKeys = zipped;
    }
}
```

Up till this use case with Micronaut it was tricky but possible to overcome this limitation by, for example, using Builder based deser so that ctor picked by **Jackson** is different than the one picked by Data.
But with this module further narrows it by not supporting builder deser.
Furthermore, something like this does not work as well.. See inline comments

```java
@Getter
@Entity
class Pojo {

    @TypeDef(type = JSON) // saved in PG as jsonb
    NavigableMap<String, Double> valuesByKeys;

    Pojo(
        NavigableMap<String, Double> valuesByKeys, // should be considered only when present as when comes from DB/Data
        // FIXME: Fails with Constructor argument [keys] for type [com.example.Pojo] must have an associated getter
        //   if we add getter SQL is like INSERT INTO "pojo" ("key","values","values_by_keys") VALUES (?,?,to_json(?::json))
        //   two pseudo columns are considered
        Collection<String> keys,  // should be considered only when present as when comes from Serde
        // FIXME: Same as with keys
        Collection<Double> values //  // should be considered only when present as when comes from Serde
    ) {
        //...zip keys a and values
        // var zipped = (keys + values)
//        this.valuesByKeys = zipped;
    }


    // FIXME: When we add @Transient it asks for getters again.
    @Transient
    public Collection<String> getPages() {
        return Objects.requireNonNullElse(getValuesByKeys(), Collections.<String, Double>emptyNavigableMap()).keySet();
    }

    @Transient
    public Collection<Double> getScores() {
        return Objects.requireNonNullElse(getValuesByKeys(), Collections.<String, Double>emptyNavigableMap()).values();
    }
}
```

We have a lot of cases like that where we need control of which ctor to pick.
This is currently quite limiting when `@JsonCreator` <-> `@Creator` mapped bidirectionally and rock-solid. Is that possible to fix this, provide a way to disambiguate? I'd say a proper idea would be that 
1. `@Creator` takes precedence for Data
2. `@JsonCreator` takes precedence for Serde

**Comment by dstepanov** [comment]
Now we use Serde also for the data persistence (MongoDB) and there is no way to have a different construction mechanism.

IMHO you are trying to use two different data models represented by one class, I would say that's not the best idea because like in this case it complicates things.

**Comment by soberich** [comment]
Got it, saw tests for mongo, reminded me about https://github.com/immutables/immutables/blob/master/criteria/mongo/README.md 
thanks, I'll leave this ambition then, though having something as priority for picking one thing over the other in case both present (e.g. `@Creator` takes precedence for Data, `@JsonCreator` takes precedence for Serde)
seems quite simple, logical and matching community expectations.
But it's up to framework authors, leave it to you, guys.
Hope this feature request helps at least to have some thoughts about the matter and maybe track it further.
