### ISSUE TITLE
Fails to serialise Parent->Child objects with JsonTypeInfo, JsonSubTypes

### ISSUE THREAD

**Issue by bowika** [micronaut-projects/micronaut-serialization#204]
### Expected Behavior

```
{"type":"SecondChild","fieldOfSecond":1,"sibling":{"name":"first", "type": "FirstChild", "fieldOfFirst": true},"name":"second"}
```

### Actual Behaviour

```
{"type":"SecondChild","fieldOfSecond":1,"sibling":{"name":"first"},"name":"second"}
```

### Steps To Reproduce

Given this Parent
```
@JsonTypeInfo(
    use = JsonTypeInfo.Id.NAME,
    property = "type")
@JsonSubTypes({
    @JsonSubTypes.Type(value = FirstChild.class, name = "FirstChild"),
    @JsonSubTypes.Type(value = SecondChild.class, name = "SecondChild")
})
@Serdeable
public class Parent {
```
Having 2 child classes
```
@Serdeable
public class FirstChild extends Parent {
    private boolean fieldOfFirst;
```
and
```
@Serdeable
public class SecondChild extends Parent {
    private int fieldOfSecond;
    private Parent sibling;
```
Then on serialising:
```
FirstChild first = (FirstChild) new FirstChild().setFieldOfFirst(true).setName("first");
SecondChild secondChild = (SecondChild) new SecondChild().setFieldOfSecond(1).setSibling(first).setName("second");
String json = mapper.writeValueAsString(secondChild);
```

Note that marking Parent as abstract makes it even worse since it tries to instantiate it.

### Environment Information

- MacOs
- Java 11.0.14-tem

### Example Application

https://github.com/bowika/micronaut-serialization-bugreport

### Version

3.4.3

**Comment by bowika** [comment]
Maybe it is easier for you, if I create a testcase in the project:
https://github.com/bowika/micronaut-serialization/commit/5c8e194a265e65c6ca5dd6a66732d7a4c095c183

**Comment by yawkat** [comment]
i think this is the same issue as #176, it's statically using the Parent as the serialization type, ignoring any customization in the subtypes

**Comment by yawkat** [comment]
ive assigned it to you @graemerocher because i think it's a design issue (the serialization should use the subtype serializer dynamically instead of sticking to the static type) and i'm not sure how to fix it

**Comment by graemerocher** [comment]
sure will take a look, need to catchup on bug fixing on this repo anyway
