### ISSUE TITLE
Would not create $xxx$IntrospectionRef0.class when add @SerdeImport into Main class or any one class that is only annotated by @Singleton

### ISSUE THREAD

**Issue by lost22git** [micronaut-projects/micronaut-serialization#276]
### Expected Behavior

create $xxx$IntrospectionRef0.class works for serde

### Steps To Reproduce

1. add @SerdeImport into Main class
![image](https://user-images.githubusercontent.com/65008815/195470256-fb5ea717-15ff-4c06-84d1-76040b019e72.png)

2. gradlew clean && gradlew build
3. check the classes dir and **$Main$IntrospectionRef0.class is not found**
![image](https://user-images.githubusercontent.com/65008815/195470138-1cd3e478-0044-4a2a-b0bf-c01c73f81dd1.png)
4. java -jar run the app and perform a  http request
5. server error
```
No serializable introspection present for 
type SystemInfo. Consider adding Serdeable. Serializable annotate to type SystemInfo. Alternatively if you are not in control of the project's source code, you can use @SerdeImport(SystemInfo.class) to enable serialization of this type.
        at io.micronaut.json.codec.MapperMediaTypeCodec.encode(MapperMediaTypeCodec.java:221)
        at io.micronaut.json.codec.MapperMediaTypeCodec.encode(MapperMediaTypeCodec.java:270)
        at io.micronaut.http.server.netty.RoutingInBoundHandler.encodeBodyAsByteBuf(RoutingInBoundHandler.java:1437)
```
6.  delete the @SerdeImport
![image](https://user-images.githubusercontent.com/65008815/195471008-cfc812cc-c1ab-45ce-bdca-2eec8b3a2db8.png)
7. gradlew build (note: do not run gradlew clean)
8. add @SerdeImport again
![image](https://user-images.githubusercontent.com/65008815/195470256-fb5ea717-15ff-4c06-84d1-76040b019e72.png)
9. gradlew build (note: do not run gradlew clean)
10. check the classes dir and **$Main$IntrospectionRef0.class is found**
![image](https://user-images.githubusercontent.com/65008815/195470120-daf7494c-f8ad-44df-ae14-ad93dbc20b67.png)
11.  java -jar run the app and perform a  http request and serde successfully

**the same problem when add @SerdeImport into any one class that is only annotated by @Singleton**

**No such problem was found when  add @SerdeImport into any one class that is annotated by @Factory or @Introspected**

### Environment Information

win11
openjdk19

### Version

3.7.1

**Comment by graemerocher** [comment]
please attach an example that reproduces the issue
