### ISSUE TITLE
Serde of Hateos JsonError can fail

### ISSUE THREAD

**Issue by chrishowell** [micronaut-projects/micronaut-serialization#285]
### Expected Behavior

Built-in Micronaut types are serdeable by default

### Actual Behaviour

io.micronaut.http.hateoas.JsonError raised a SerdeException.
![Screenshot 2022-10-18 at 18 54 39](https://user-images.githubusercontent.com/1407962/196507925-f6dd0da9-9f6e-4ca8-8e45-4a32f7d8fffe.png)

### Steps To Reproduce

I passed an invalid enum value to a record with an enum property, where the record was annotated `@Serdeable`, serialisation failed but then through a `SerdeException` for `JsonError`.
I tried to annotate my `Application` class with `@SerdeImport(JsonError.class)` but this had no effect.
Adding breakpoints on 'any Exception' is how I found out that this was triggered by an invalid enum value.

### Version

3.8.0-SNAPSHOT

**Comment by chrishowell** [comment]
Ahh I think I've figured out what's causing it. I'm not sure if this is a bug in the code, but it's at least unclear in the documentation that when you specify a `micronaut.serde.included-introspection-packages` property that this isn't additive.

**Comment by graemerocher** [comment]
if you can provide an example maybe we can look into it more
