### ISSUE TITLE
:doc-examples:example-kotlin:nativeCompile  fails in master

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-serialization#295]
### Issue description

see: https://ge.micronaut.io/s/vkw43dbbnzyai
[3210](https://github.com/micronaut-projects/micronaut-serialization/actions/runs/3344985082/jobs/5539969650#step:6:3211)

**Comment by dstepanov** [comment]
@graemerocher Did we remove some native configs in the Core?

**Comment by graemerocher** [comment]
yes native config changed, but the nettyfeature is still there
