### ISSUE TITLE
Serialization doesn't work with micronaut-data Page response

### ISSUE THREAD

**Issue by timyates** [micronaut-projects/micronaut-serialization#307]
### Feature description

There is a repo here which attempts to use `micronaut-data` with `micronaut-serialization` via the pagination support offered by `Page`

https://github.com/timyates/serdeable-data-page

The [controller method](https://github.com/timyates/serdeable-data-page/blob/517589709468fe52b96c55bff1ea7d599eb87547/src/main/java/com/example/WidgetController.java#L17-L20) returns a `Page<WidgetDTO>`

However, when the database is empty, only an empty list `[]` is returned as JSON as shown by this test

https://github.com/timyates/serdeable-data-page/blob/master/src/test/groovy/com/example/WidgetControllerSpec.groovy

Not a JSON representation of [`Page`](https://github.com/micronaut-projects/micronaut-data/blob/master/data-model/src/main/java/io/micronaut/data/model/Page.java) (or the internal class [`DefaultPage`](https://github.com/micronaut-projects/micronaut-data/blob/master/data-model/src/main/java/io/micronaut/data/model/DefaultPage.java) which is the class returned by the controller method)

**Comment by graemerocher** [comment]
PR sent to data here https://github.com/micronaut-projects/micronaut-data/pull/1825 but will require changes here too

**Comment by stmty9** [comment]
wouldn't it make more sense to add a similar pageable class outside of micronaut data (maybe in one of the core libs) to have a cleaner separation of layers?

**Comment by dstepanov** [comment]
I have created a custom serializer to avoid this problem https://github.com/micronaut-projects/micronaut-data/pull/1753/commits/1190f94e0286f773d21e805531f61cb23a7e18fa
It looks like the iterable serializer is always pickup because it's implemented by `Page/Slice`.

**Comment by graemerocher** [comment]
Define a serializer like this https://github.com/micronaut-projects/micronaut-data/commit/1190f94e0286f773d21e805531f61cb23a7e18fa

**Comment by GyrosOfWar** [comment]
> Define a serializer like this [micronaut-projects/micronaut-data@1190f94](https://github.com/micronaut-projects/micronaut-data/commit/1190f94e0286f773d21e805531f61cb23a7e18fa)

I tried that, but `DefaultPage` is a package-private class, and writing the serializer for `Page<Object>` instead doesn't seem to work.

**Comment by bogdan23a** [comment]
Any luck guys?

**Comment by graemerocher** [comment]
will be fixed in the next milestone for 4.x

**Comment by sdelamo** [comment]
This is solved in Micronaut Framework 4 https://github.com/timyates/serdeable-data-page/pull/1
