### ISSUE TITLE
Kotlin test failing in `micronaut-rabbitmq` with `SerializationException decoding JSON stream`

### ISSUE THREAD

**Issue by wetted** [micronaut-projects/micronaut-serialization#363]
### Expected Behavior

The PR at https://github.com/micronaut-projects/micronaut-rabbitmq/pull/434 enables running the `docs-examples` tests on the master branch for Micronaut 4.

The Kotlin test at https://github.com/micronaut-projects/micronaut-rabbitmq/blob/master/docs-examples/example-kotlin/src/test/kotlin/io/micronaut/rabbitmq/docs/exchange/CustomExchangeSpec.kt should pass. It does on the branch targeting Micronaut 3.

### Actual Behaviour

`Caused by: io.micronaut.core.serialize.exceptions.SerializationException: Error decoding JSON stream for type [snake]: Unable to deserialize type [io.micronaut.rabbitmq.docs.exchange.Snake]. Required constructor parameter [boolean venomous] at index [1] is not present or is null in the supplied data`

Note the following code.`Cat` objects work fine in the test, but `Snake` objects raise the noted exception. 

The test creates the objects 
```
    client.send(Cat("Whiskers", 9))
    client.send(Cat("Mr. Bigglesworth", 8))
    client.send(Snake("Buttercup", false))
    client.send(Snake("Monty the Python", true))
```

with the following class definitions

```
abstract class Animal {

    var name: String? = null

    constructor(name: String) {
        this.name = name
    }

    constructor() {}
}
```

```
@Serdeable
class Snake : Animal {

    var isVenomous: Boolean = false

    constructor(name: String, venomous: Boolean) : super(name) {
        this.isVenomous = venomous
    }

    constructor() {}
}
```

```
@Serdeable
class Snake : Animal {

    var isVenomous: Boolean = false

    constructor(name: String, venomous: Boolean) : super(name) {
        this.isVenomous = venomous
    }

    constructor() {}
}
```

@timyates notes that it seems to work with the more idiomatic definitions, as follows. I have confirmed it as well.

```
abstract class Animal(var name: String? = null) {
}
```
```
@Serdeable
class Cat(name: String? = null, lives: Int = 0) : Animal(name) {
}
```
```
@Serdeable
class Snake(name: String? = null, venomous: Boolean = false) : Animal(name) {
}
```

### Environment Information

macOS Ventura 13.2
java version 17.0.6-tem

### Example Application

https://github.com/micronaut-projects/micronaut-rabbitmq/pull/434

### Version

4.0.0-SNAPSHOT

**Comment by sdelamo** [comment]
@wetted is this still pending?

**Comment by wetted** [comment]
> @wetted is this still pending?

I don't know. In the referenced PR (now merged) the kotlin classes were changed to the more idiomatic forms that work. I can investigate if this is still an issue when I get back after the holiday weekend..

**Comment by wetted** [comment]
This is no longer an issue. I ran the example test with both versions of the POJO classes and it passes either way.
