### ISSUE TITLE
Is package publishing to maven repository working properly?

### ISSUE THREAD

**Issue by dumbNickname** [micronaut-projects/micronaut-serialization#379]
### Issue description

Hi there,

I have been trying to update the micronaut serde dependency to 1.5 because I saw in the release notes that it includes a feature I would like to use (available since 1.3.3, related to EnumSerde extensions). Unfortunately, my test still did not go green. I confirmed in the github source that it contains exactly what I need, but when I download the jar sources I still see a very old implementation of EnumSerde. I checked here https://repo1.maven.org/maven2/io/micronaut/serde/micronaut-serde-support/1.5.0/ by manually downloading the file [micronaut-serde-support-1.5.0-sources.jar](https://repo1.maven.org/maven2/io/micronaut/serde/micronaut-serde-support/1.5.0/micronaut-serde-support-1.5.0-sources.jar). When I unzip the jar and go to the EnumSerde implementation I see the old one as well (not what I would expect when looking at github sources). 

As a final check, I copy and paste the EnumSerde implementation available on the current master branch and annotated it with @ Primary. Now my test is green. At first I thought that only the sources were wrongly attached, but maybe the whole package does not really contain what ppl think it should contain? 

I really hope I am wrong or I missed something (in which case any advice would be appreciated, please excuse for bothering you), but I thought I would report this issue so that smarter people can check if package publishing works exactly as expected (and that e.g. sb does not accidentally override new releases with some old jars). 

Thanks in advance for any feedback! 

P.S. It looks like micronaut is my new friend, so if there are better channels to report / ask about such issues - please let me know as well :)

**Comment by domlen2003** [comment]
Same problem here, copied the tests from the [pull request](https://github.com/micronaut-projects/micronaut-serialization/pull/395/files#diff-3a5cefcdad04950176d441212c0b5e5dc41be9e8020842077cd301c91202b723) that added the feature and ran it with `implementation("io.micronaut.serde:micronaut-serde-jackson:1.5.2)` and the tests failed.

**Comment by graemerocher** [comment]
yeah these changes only went into 1.5.x in 1.5.2 I believe. Just updating one dependency is probably not enough, you need to probably add `implementation("io.micronaut.serde:micronaut-serde-support:1.5.2)`

**Comment by domlen2003** [comment]
Yeah not even that works...

**Comment by domlen2003** [comment]
That also doesn't work. 
I added the dependency, ran the same tests and still didn't get the right results.
Tho I digged a bit deeper and looked into the introspection of the test Foo enum:
```java
static {
    $FIELD_CONSTRUCTOR_ANNOTATION_METADATA = new DefaultAnnotationMetadata(
            AnnotationUtil.mapOf(
                    "com.fasterxml.jackson.annotation.JsonCreator", Collections.EMPTY_MAP,
                    "io.micronaut.core.annotation.Creator", Collections.EMPTY_MAP
            ),
            AnnotationUtil.mapOf(
                    "com.fasterxml.jackson.annotation.JacksonAnnotation", Collections.EMPTY_MAP
            ),
            AnnotationUtil.mapOf(
                    "com.fasterxml.jackson.annotation.JacksonAnnotation", Collections.EMPTY_MAP
            ),
            AnnotationUtil.mapOf(
                    "com.fasterxml.jackson.annotation.JsonCreator", Collections.EMPTY_MAP,
                    "io.micronaut.core.annotation.Creator", Collections.EMPTY_MAP
            ),
            AnnotationUtil.mapOf(
                    "com.fasterxml.jackson.annotation.JacksonAnnotation", AnnotationUtil.internListOf(new Object[{"com.fasterxml.jackson.annotation.JsonCreator"})
            ),
            false,
            true
    );
    $CONSTRUCTOR_ARGUMENTS = new Argument[]{Argument.of(
            String.class,
            "value",
            new DefaultAnnotationMetadata(
                    AnnotationUtil.mapOf(
                            "javax.annotation.Nullable", Collections.EMPTY_MAP
                    ),
                    Collections.EMPTY_MAP,
                    Collections.EMPTY_MAP,
                    AnnotationUtil.mapOf(
                            "javax.annotation.Nullable", Collections.EMPTY_MAP
                    ),
                    Collections.EMPTY_MAP,
                    false,
                    true
            ),
            (Argument[]) null
    )};
}
```
It doesn't contain any mention of this method:
```java
@JsonValue
public String toString() {
    return this.value;
}
```

**Comment by dstepanov** [comment]
Please try your issue in the latest release
