### ISSUE TITLE
Serde M4 fails in micronaut-security

### ISSUE THREAD

**Issue by timyates** [micronaut-projects/micronaut-serialization#440]
We had an issue in security with M3 whereby unknown properties in the json would cause deserialization to fail.

This was fixed in https://github.com/micronaut-projects/micronaut-serialization/pull/439 and M4 was released

Tried to update to use the new M4 of serde in https://github.com/micronaut-projects/micronaut-security/pull/1303, and we're getting test failures in the oauth module

https://ge.micronaut.io/s/xgizhyx4r22hq/tests/overview?outcome=failed

It seems to be a NPE in io.micronaut.json.convert.JsonConverterRegistrar.lambda$mapToObjectConverter$2 [here](https://github.com/micronaut-projects/micronaut-core/blob/1432dc527b75508889e83d7b1b82d7dba8b527bd/json-core/src/main/java/io/micronaut/json/convert/JsonConverterRegistrar.java#L179)

The error is shown (on a single line) [in the build scan](https://ge.micronaut.io/s/xgizhyx4r22hq/tests/:micronaut-security-oauth2:test/io.micronaut.security.oauth2.client.clientcredentials.ClientCredentialsConcurrentSpec/no%20exception%20for%20concurrent%20requests%20using%20client%20credentials?focused-execution=2&top-execution=3#L19)

**Comment by timyates** [comment]
My original PR was closed in favor of https://github.com/micronaut-projects/micronaut-security/pull/1304

Where @sdelamo extracted a form out to get the tests to pass with M4

**Comment by sdelamo** [comment]
I created an issue for what I found upgrading security to M4 https://github.com/micronaut-projects/micronaut-serialization/issues/441
