### ISSUE TITLE
Annotation @JsonProperty not working for enums

### ISSUE THREAD

**Issue by cogam** [micronaut-projects/micronaut-serialization#503]
### Expected Behavior

I expect to use `@JsonProperty` to control the serialization of a enum value.

### Actual Behaviour

`@JsonProperty` is silently ignored.

### Steps To Reproduce

Given a class (import omitted)

```
@Serdeable
public enum MyEnum {

  @JsonProperty("value")
  VALUE;
}
```
and a test case

```
import io.micronaut.serde.ObjectMapper;
import io.micronaut.test.extensions.junit5.annotation.MicronautTest;
import org.junit.jupiter.api.Test;

import java.io.IOException;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;


@MicronautTest
class MyEnumSerdeTest {

@Test
  void testSerialization(ObjectMapper objectMapper) throws IOException {
    String output = objectMapper.writeValueAsString(MyEnum.VALUE);

    assertNotNull(output);
    assertEquals("\"value\"", output);
  }
```

### Environment Information

OS: Ubuntu 22.04 LTS
Versions:
implementation("io.micronaut.serde:micronaut-serde-jackson:2.0.0-M12")
annotationProcessor("io.micronaut.serde:micronaut-serde-processor:2.0.0-M12")

### Version

4.0.0-M3

**Comment by chrisparton1991** [comment]
@cogam can you use `@JsonValue` instead? Something like below:

```
@Serdeable
public enum MyEnum {
    VALUE("value");

    @JsonValue
    private String value;

    MyEnum(String value) {
        this.value = value;
    }
}
```

**Comment by dirkhas** [comment]
> @cogam can you use `@JsonValue` instead? Something like below:
> 
> ```
> @Serdeable
> public enum MyEnum {
>     VALUE("value");
> 
>     @JsonValue
>     private String value;
> 
>     MyEnum(String value) {
>         this.value = value;
>     }
> }
> ```

The @JsonValue method only works for serialization, not for deserialization with the current EnumSerde implementation. (Except, of course, if the json value by chance happens to be a lower-case version of the enum param value -- which is what makes the current tests pass. See [here](https://github.com/micronaut-projects/micronaut-serialization/pull/298/files#diff-195e73aedaa41a799f8b1c916fc078f85f06375600f610076add91b02dcb262bR60-R63) in the original @JsonValue PR for that weird behavior.)

**Comment by altro3** [comment]
@dstepanov any news about this? It's important, because if you want to use micronaut-openapi, you need to set `@JsonProperty` annotation for every enum value, because micronaut-openapi can't run method `@JsonValue`. Now the single solution for correct work - need to set `@JsonProperty` annotations and `@JsonCreator` / `@JsonValue` annotation together
