### ISSUE TITLE
The Jackson annotations @JsonIgnore and @JsonIgnoreProperties do not work with Micronaut Serialization even though they are specified as supported in the documentation

### ISSUE THREAD

**Issue by runenielsen** [micronaut-projects/micronaut-serialization#548]
### Expected Behavior

I expect properties in a model marked with `@JsonIgnore` or `@JsonIgnoreProperties` (on class level) annotations to be omitted from serialization and deserialization when using Micronaut Serialization, just like they are when using Jackson Databind.

The annotations are supposed to be supported by Micronaut Serialization according to the [documentation](https://micronaut-projects.github.io/micronaut-serialization/latest/guide/index.html).

### Actual Behaviour

The annotations `@JsonIgnore` and `@JsonIgnoreProperties` seem to have no effect.

### Steps To Reproduce

1. Clone the project https://github.com/runenielsen/jsonignorenotworking
2. Run the `JsonIgnoreTest` test class.
3. The test cases testing serialization and deserialization with `@JsonIgnore` and `@JsonIgnoreProperties` using Micronaut Serialization are failing, and the identical test cases using Jackson Databind are succeeding.

### Environment Information

OS: MacOs
JDK: 17

But this should fail on any environment.

### Example Application

https://github.com/runenielsen/jsonignorenotworking

### Version

4.0.3

**Comment by yawkat** [comment]
youre missing a testAnnotationProcessor

**Comment by runenielsen** [comment]
@yawkat : Thanks. Sorry, my bad.

I do actually have a real bug, I believe. I just tried to simplify the case as much as possible, but apparently it was too much.

I will update the reproduction project with the testAnnotationProcessor and create a new issue with the readl bug.
