### ISSUE TITLE
property-naming-strategy (and other jackson configurations) not respected

### ISSUE THREAD

**Issue by facup94** [micronaut-projects/micronaut-serialization#552]
### Expected Behavior

Micronaut Serialization module should respect Jackson property naming strategy settings (from application.yml) when serializing/deserializing POJOs

### Actual Behaviour

Micronaut ignores Jackson settings

### Steps To Reproduce

1. create an app with jackson features
`mn create-app --build=gradle --jdk=17 --lang=java --test=junit --features=serialization-jackson,jackson-databind com.example.demo`
2. Add a controller with an endpoint that receives a POJO
```java
// HelloController.java
@Controller
public class HelloController {
    @Post("/hello1")
    @Produces(MediaType.APPLICATION_JSON)
    public String index(@Body Hello1Request req) {
        return "Hello1, " + req.firstName();
    }
}

// Hello1Request.java
@Serdeable
public class Hello1Request {
    private final String firstName;

    public Hello1Request(final String firstName) {
        this.firstName = firstName;
    }

    public String firstName() {
        return firstName;
    }
}
```

3. Add `jackson.property-naming-strategy: SNAKE_CASE` to `application.yml`
4. Start the app
5. Send a request using snake case: `curl -X POST 'http://localhost:8080/hello1' -H 'Content-Type: application/json' -d '{"first_name": "John"}'`
6. Receive error: `{"message":"Bad Request","_links":{"self":[{"href":"/hello1","templated":false}]},"_embedded":{"errors":[{"message":"Failed to convert argument [req] for value [null] due to: Unable to deserialize type [Hello1Request req]: Null argument specified for [firstName]. If this argument is allowed to be null annotate it with @Nullable","path":"/req"}]}}%`
7. Send a request using lower camel case: `curl -X POST 'http://localhost:8080/hello1' -H 'Content-Type: application/json' -d '{"firstName": "John"}'`
8. receive OK response: `Hello1, John`

### Environment Information

- macOS Monterrey 12.6.6
- Java 17
- Micronaut 3.10.1

### Version

3.10.1

**Comment by facup94** [comment]
> you should not use both features `serialization-jackson` and `jackson-databind`
> 
> [With Micronaut Framework 4.0, you must choose which serialization implementation you want.](https://micronaut.io/2023/02/27/micronaut-framework-4-0-and-micronaut-jackson-databind-transitive-dependency/).
> 
> I don't expect Micronaut Serialisation to use Jackson configuration such as `jackson.property-naming-strategy: SNAKE_CASE`
> 
> You can access the [Micronaut Serialization configuration reference](https://micronaut-projects.github.io/micronaut-serialization/latest/guide/configurationreference.html) and [Micronaut Serialization docs](https://micronaut-projects.github.io/micronaut-serialization/latest/guide/index.html).

The issue I reported was for Micronaut 3.10.1 but thanks for your response.

I understand Micronaut Serialization does not have a configuration for naming strategy then

**Comment by sdelamo** [comment]
> I understand Micronaut Serialization does not have a configuration for naming strategy then

I don't think we do. Do you know @yawkat ?

**Comment by graemerocher** [comment]
currently it can be done on an individual type level but not globally no

**Comment by abishai** [comment]
We have even worse issue with Micronaut Serialization feature. We have JDBI as a ResultSet to POJO mapper and extensively using PG json functions. The problem is databases are usually snake cased, so we are injecting a copy of Jackson ObjectMapper with custom SNAKE_CASE strategy in Micronaut3 microservices. 

With Micronaut's ObjectMapper is totally impossible by design (it reads @Serdeable annotation to determine strategy - and we use default for anything except database interaction). 

Can we get back the ability to globally override strategy for concrete ObjectMapper instance?
