### ISSUE TITLE
Depth limit not decremented in array of objects

### ISSUE THREAD

**Issue by sosguthorpe** [micronaut-projects/micronaut-serialization#557]
### Expected Behavior

Fetching a page of 2000 shallow (2 objects deep max) in a JSON array should be comfortably serialised with default limit.

### Actual Behaviour

Nesting limit of being exceeded, and exception `io.micronaut.serde.exceptions.SerdeException: Maximum depth exceeded while deserializing.` is thrown.

I have actually traced this to  the JacksonDecoder overriding the interface's default version of `finishStructure` with no args:
https://github.com/micronaut-projects/micronaut-serialization/blob/master/serde-jackson/src/main/java/io/micronaut/serde/jackson/JacksonDecoder.java#L118

Without decreasing the depth again. So the number of elements is incorrectly contributing to the max depth value. The fix should be to either remove this override and drop back to the Decoder interface's default, or decreasing the depth in this method.

I would have contributed this but given the class is final I wasn't sure how to easily override the decoder to test properly.

### Version

4.0.5

**Comment by yawkat** [comment]
thanks for the report and tracking down the cause!
