### ISSUE TITLE
Unexpected behavior when using JsonTypeInfo.As.WRAPPER_OBJECT (attribute order dependant)

### ISSUE THREAD

**Issue by ricantech** [micronaut-projects/micronaut-serialization#575]
### Expected Behavior

When using WRAPPER_OBJECT the serialization and deserialization should not be dependant on attribute order. 
If the class is defined as:
```
@Serdeable
class Message {
    @JsonProperty("id") lateinit var id: String
    @JsonProperty("direction") lateinit var direction: String
    @JsonProperty("contact_message") lateinit var contactMessage: ContactMessage
    @JsonProperty("conversation_id") var conversationId: String? = null
    @JsonProperty("contact_id") var contactId: String? = null
}

@Serdeable
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.WRAPPER_OBJECT)
@JsonSubTypes(
    JsonSubTypes.Type(value = TextMessage::class),
    JsonSubTypes.Type(value = UrlMessage::class)
)
open class ContactMessage

@Serdeable
@JsonTypeName("text_message")
class TextMessage: ContactMessage() {
    @JsonProperty("text") lateinit var text: String
}
```
and I'll create object as:
```
Message().also {
                it.id = "message-id"
                it.direction = "direction"
                it.conversationId = "conversation-id"
                it.contactId = "contact-id"
                it.contactMessage = TextMessage().also { it.text = "Body" }
            }
```
I would expect the generated JSON will look as follows:
```
"message": {
    "id": "message-id",
    "direction": "direction",
    "contact_message": {
      "text_message": {
        "text": "body"
      }
    },
    "conversation_id": "conversation-id",
    "contact_id": "contact-id"
  }
```

Same applies to deserializatin. If I try to read JSON above and convert it to object I would expect all attributes to be filled in if present on object.

### Actual Behaviour

What happens at the moment for deserialization is as follows.
I'm having defined those classes
```
@Serdeable
class Message {
    @JsonProperty("id") lateinit var id: String
    @JsonProperty("direction") lateinit var direction: String
    @JsonProperty("contact_message") lateinit var contactMessage: ContactMessage
    @JsonProperty("conversation_id") var conversationId: String? = null
    @JsonProperty("contact_id") var contactId: String? = null
}

@Serdeable
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.WRAPPER_OBJECT)
@JsonSubTypes(
    JsonSubTypes.Type(value = TextMessage::class),
    JsonSubTypes.Type(value = UrlMessage::class)
)
open class ContactMessage

@Serdeable
@JsonTypeName("text_message")
class TextMessage: ContactMessage() {
    @JsonProperty("text") lateinit var text: String
}
```
when I'm trying to de-serialize the JSON like this
```
"message": {
    "id": "message-id",
    "direction": "direction",
    "contact_message": {
      "text_message": {
        "text": "body"
      }
    },
    "conversation_id": "conversation-id",
    "contact_id": "contact-id"
  }
```
My object will have all attributes after `contact_message` equal to `null` (conversation_id and contact_id) at this example.

### Steps To Reproduce

See the attached repository

If more information needed. Please let me know!

### Environment Information

OS: Fedora Linux 38 (Workstation Edition) x86_64
Kernel: 6.4.7-200.fc38.x86_64

openjdk version "17.0.5" 2022-10-18
OpenJDK Runtime Environment GraalVM CE 22.3.0 (build 17.0.5+8-jvmci-22.3-b08)
OpenJDK 64-Bit Server VM GraalVM CE 22.3.0 (build 17.0.5+8-jvmci-22.3-b08, mixed mode, sharing)

### Example Application

https://github.com/ricantech/micronaut-serde-wrapper-object

### Version

4.1.1

**Comment by ricantech** [comment]
Hi, 

had some time so did some debugging and it seems to be breaking on
`io.micronaut.serde.support.deserializers.SpecificObjectDeserializer#finalizeObjectDecoder` where we are calling `finalizeObjectDecoder` as when it finalize the object decoder with `finishStructure(true)` it `decreseDepth` just by one.

That leads to to inconsistency on `SimpleObjectDeserializer` which returns that `allConsumed == false` and cycle continue but as we are currently on incorrect depth the call to `objectDecoder.decodeKey()` returns null and it stops the object de-serialization (if I decrese depth manually in debugger it de-serialize the object just fine)

**Comment by graemerocher** [comment]
@yawkat sounds like a JSON decoding issue, could you take a look?

**Comment by yawkat** [comment]
Thanks for the report!

**Comment by ricantech** [comment]
Thank you for quick action. Glad to help.
