### ISSUE TITLE
Micronaut Serialization Opt-Out

### ISSUE THREAD

**Issue by thobiaskarlsson** [micronaut-projects/micronaut-serialization#577]
### Feature description

**Background**
We've been in production with Micronaut in several AWS Lambdas for a couple of years now. When migrating to 4.0 we met unexpected difficulties regarding JSON serialization and deserialization. With Micronaut Serialization, a.k.a. introduction of the "serde" stuff, suddenly libraries using raw Jackson started to fail and also all AWS `RequestHandler` started failing with `null` as input parameters (for instance `SQSEvent`). We've tried to do as suggested best practices, including annotating with `@Serdeable` etc everywhere but this forces us into an uncomfortable situation, i.e. having all shared libraries/components within the company being dependant on Micronaut. The changes due to this version update cascade across our entire technical stack, which is a non-starter.

**Feature Request**
To be able to _entirely_ opt-out from Micronaut Serialization and use raw Jackson as before. We are aware that this might be _a bit_ more costly with higher latencies etc, but it's marginal hence worth it. The choice of serialization library/-mechanism should be left to the users of Micronaut.

**Comment by yawkat** [comment]
you can already do this by depending on micronaut-jackson-databind instead of io.micronaut.serialization.
