### ISSUE TITLE
@JsonRootName is not working with @Serdeable.Serializable

### ISSUE THREAD

**Issue by stanleyw2014** [micronaut-projects/micronaut-serialization#587]
### Expected Behavior

I have a class annotated with @Serdeable.Serializable:

@Serdeable.Serializable
public class SampleClass {
private String a;
private String b;
.....
}
it is serialized as {"a":"ddd", b:"vvv"}
I want it to be {"sampleClass": {"a":"ddd", b:"vvv"}}

### Actual Behaviour

I added @JsonRootName(value = "sampleClass") before class name, but it is not working, the response sill :
{"a":"ddd", b:"vvv"}

### Version

4.1.1

**Comment by stanleyw2014** [comment]
Hi, 
I saw this issue was tagged as enhancement, is there any walk around in 4.1.1 to set json root of an object?

**Comment by yawkat** [comment]
No, there is no workaround beyond just changing your model or making a custom serializer. We just haven't implemented all jackson features.

**Comment by graemerocher** [comment]
only work around I can think of is to use is to use `@JsonTypeInfo` with `WRAPPER_OBJECT` which is supported. See https://fasterxml.github.io/jackson-annotations/javadoc/2.12/com/fasterxml/jackson/annotation/JsonTypeInfo.As.html#WRAPPER_OBJECT

see https://www.logicbig.com/tutorials/misc/jackson/json-type-info-with-logical-type-name.html

**Comment by stanleyw2014** [comment]
> only work around I can think of is to use is to use `@JsonTypeInfo` with `WRAPPER_OBJECT` which is supported. See https://fasterxml.github.io/jackson-annotations/javadoc/2.12/com/fasterxml/jackson/annotation/JsonTypeInfo.As.html#WRAPPER_OBJECT
> 
> see https://www.logicbig.com/tutorials/misc/jackson/json-type-info-with-logical-type-name.html

I tried this, not working either…

**Comment by dstepanov** [comment]
Fixed by https://github.com/micronaut-projects/micronaut-serialization/pull/613
