### ISSUE TITLE
Allow polymorphism to use existing attribute

### ISSUE THREAD

**Issue by KangoV** [micronaut-projects/micronaut-serialization#664]
### Feature description

I'm trying to migrate to Micronaut Validation of a project that de/serialises STIX 2.1. This format is a very flat object model. The type of each object is an existing attribute in each object. For example:

```
{
    "type": "bundle",
    "id": "bundle--2ac7882f-76a3-4a9b-97b3-811b3af1c7c0",
    "objects": [
        {
            "type": "indicator",
            "id": "indicator--9299f726-ce06-492e-8472-2b52ccb53191",
            ...
        },
        {
            "type": "identity",
            "id": "identity--39012926-a052-44c4-ae48-caaf4a10ee6e",
            ...
        }
    ]
}
```

The problem is that currently, `@JsonTypeInfo(include=JsonTypeInfo.As.EXISTING_PROPERTY)` is not supported. If `JsonTypeInfo.As.PROPERTY` is used, the attribute `@type` is added, which goes against the STIX specification.

Also, `@JsonTypeInfo.visible` attribute is not supported. This needs to be set to true to enable the field to be deserialised. 

This all works in Jackson. Is there any way around this?

**Comment by dstepanov** [comment]
In the latest version, you can use:
```
@JsonIgnoreProperties(
  value = "type",
  allowSetters = true
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "type", visible = true)
```

**Comment by KangoV** [comment]
Ahh nice. Yes, I just set version to latest and this does work. Uncovered another issue though which I'll post. Thanks.

**Comment by dstepanov** [comment]
I will have it open to implement it
