### ISSUE TITLE
Bugs with discrimantor with kotlin classes

### ISSUE THREAD

**Issue by altro3** [micronaut-projects/micronaut-serialization#665]
Bug  https://github.com/micronaut-projects/micronaut-serialization/issues/649 fixed only for java. Now we have a problem with kotlin with kapt classes. Look to reproduce example here (branch `kotlin`): https://github.com/altro3/micronaut3-bug/tree/kotlin

First you can check serialization bug: 

![изображение](https://github.com/micronaut-projects/micronaut-serialization/assets/48474279/05ae5b44-af30-483e-96a8-65d55aaccdf6)

Call `/test` endpoint with body like this:
```json
{
  "class": "ave",
  "numWings": 2,
  "beakLength": 12.1,
  "featherDescription": "Large blue and white feathers"
}
```

Second bug with deserialization: just call /start endpoint and you will see exception:

![изображение](https://github.com/micronaut-projects/micronaut-serialization/assets/48474279/3534f620-5e24-486e-8f44-10453c266794)

### Version

4.2.0

**Comment by altro3** [comment]
@dstepanov could you look?

**Comment by dstepanov** [comment]
You need to define the annotations on the field `@field:JsonProperty(JSON_PROPERTY_PROPERTY_CLASS)`

**Comment by altro3** [comment]
ok, yes with this change it works. What about other jackson annotations? Like `@JsonInclude` and `@JsonFormat`. Do I need to add `field` prefix for them too?

**Comment by dstepanov** [comment]
You should

**Comment by altro3** [comment]
Same question about jakarta.validation annotations

**Comment by dstepanov** [comment]
I think those can be on the constructor parameters to be validated.

**Comment by altro3** [comment]
ok, understand
