### ISSUE TITLE
JsonProperty read/write access does not work as expected

### ISSUE THREAD

**Issue by Sebo11** [micronaut-projects/micronaut-serialization#717]
### Expected Behavior

Hello everyone, 

I currently work with serdeable and have this strange behavior for my DTO in connection with the controller (See below for example). When I make a POST request on it, both parameters are read when set. However, in the response only `fieldWrite` is returned and the `fieldRead` is omitted somehow. 

What I would expect at the moment is, that the property `fieldWrite` is the only one which should be read from the request body and `fieldRead` should be the only value returned. Can someone check that please? 

```
import io.micronaut.serde.annotation.Serdeable
import java.util.UUID
import com.fasterxml.jackson.annotation.JsonProperty

@Serdeable
data class ExampleDTO(
    @JsonProperty(access = JsonProperty.Access.READ_ONLY)
    val fieldRead: UUID?,
    @JsonProperty(access = JsonProperty.Access.WRITE_ONLY)
    val fieldWrite: UUID?,
)
```

```
import io.micronaut.http.annotation.Controller
import io.micronaut.http.annotation.Post

@Controller
class ExampleController {
    @Post
    fun example(
        userId: String,
        @Body exampleDTO: ExampleDTO
    ): HttpResponse<ExampleDTO> {
        println(exampleDTO)
        // output: ExampleDTO(fieldRead=66dac47f-8698-4f55-a737-34c71a15d8ec, fieldWrite=66dac47f-8698-4f55-a737-34c71a15d8ec)
        return HttpResponse.ok(exampleDTO)
    }
}

// respone: {"fieldWrite": "4eb61137-9f8b-4975-b0ed-9d2714596fb4"}
```

Best wishes, Sebastian

### Actual Behaviour

When using `JsonProperty.Access.READ_ONLY` for a field in a DTO, the field is omitted in the response. When using `JsonProperty.Access.WRITE_ONLY` it does not seem to have any effect at all (always read and written). 

### Environment Information

- JDK Java 21
- Micronaut 4.2.2
- gradle 8.4
- Kotlin 1.9.21

### Version

4.2.2

**Comment by dstepanov** [comment]
That should be fixed in the next platform release

**Comment by Sebo11** [comment]
> Please check the latest release

thanks ;)

**Comment by Sebo11** [comment]
Hello, i just tried it out with following dependency
```
implementation("io.micronaut.serde:micronaut-serde-jackson:2.8.1")
```

The annotation 
```
    @JsonProperty(access = JsonProperty.Access.WRITE_ONLY)
```
works now as expected. However, the annotation 
```
    @JsonProperty(access = JsonProperty.Access.READ_ONLY)
```
does not have an effect now. So for `READ_ONLY` the properties are read and written.

**Comment by Sebo11** [comment]
@dstepanov I guess there might still be an error maybe?

**Comment by dstepanov** [comment]
Please create an example project where it doesn't work.

**Comment by Sebo11** [comment]
Hello, I created now an example project with the latest micronaut version. 

https://github.com/Sebo11/MicronautJsonProperty

I just tested it again. When I invoke a `POST` request on this method below. Both params are deserialized. 
``` 
@Post
    fun examplePost(@Body exampleDto: ExampleDto): ExampleDto {
        println(exampleDto)
        return exampleDto
    }
``` 

for this DTO

```
@Serdeable
data class ExampleDto(
    @JsonProperty(access = JsonProperty.Access.READ_ONLY)
    private val readElement: String?,
    @JsonProperty(access = JsonProperty.Access.WRITE_ONLY)
    private val writeElement: String?
)
```

The output of `println` is 
```
ExampleDto(readElement=testRead, writeElement=testWrite)
```

The response however is the empty object somehow.
