### ISSUE TITLE
JsonFormat annotation should not require use-site targets in kotlin data classes

### ISSUE THREAD

**Issue by CheeseSucker** [micronaut-projects/micronaut-serialization#727]
### Expected Behavior

The following code used to work in Micronaut 3 using Jackson.

```kotlin
import com.fasterxml.jackson.annotation.JsonFormat
import io.micronaut.serde.ObjectMapper
import io.micronaut.serde.annotation.Serdeable
import io.micronaut.test.extensions.junit5.annotation.MicronautTest
import org.junit.jupiter.api.Assertions.*
import org.junit.jupiter.api.Test
import java.time.LocalDateTime

@Serdeable
data class MyKotlinClass(
    @JsonFormat(pattern = "yyyy-MM-dd HH")
    val value: LocalDateTime
)


@MicronautTest
class JsonFormatTest(val objectMapper: ObjectMapper) {
    @Test
    fun serializesCorrectly() {
        val original = MyKotlinClass(LocalDateTime.of(1990, 12, 31, 0, 0, 0))
        val serialized = objectMapper.writeValueAsString(original)
        assertEquals("""{"value":"1990-12-31 00"}""", serialized)
    }

    @Test
    fun deserializesCorrectly() {
        val json = """{"value":"1990-12-31 00"}"""
        val deserialized = objectMapper.readValue(json, MyKotlinClass::class.java)

        assertEquals(
            LocalDateTime.of(1990, 12, 31, 0, 0, 0),
            deserialized.value
        )
    }
}
```

Class should be serialized to `{"value":"2000-12-31 00"}` and both tests should pass.

### Actual Behaviour

- Serialization fails:
   > Expected: `{"value":"1990-12-31 00"}`
   > Actual: `{"value":"1990-12-31T00:00:00"}`
- Deserialization passes, which is strange. Removing the JsonFormat annotation makes the deserialization fail as well.

Adding `@field:JsonFormat(...)` makes the tests pass.
```kotlin
@Serdeable
data class MyKotlinClass(
    @JsonFormat(pattern = "yyyy-MM-dd HH")
    val value: LocalDateTime
)
``` 

### Environment Information

- Micronaut 4.2.3
- Micronaut Serde 2.4.0
- Kotlin 1.9.20
- Annotation processor: kapt

### Version

4.2.3

**Comment by graemerocher** [comment]
this is a limitation of KAPT, not sure we can do about it

**Comment by altro3** [comment]
@CheeseSucker Use KSP instead kapt: with KSP you can write annotations withou `field:` prefix

**Comment by altro3** [comment]
@graemerocher @dstepanov I think, you can close this issue. As you said - with KAPT we can't use annotaions without scope, but with SKP allworks fine without `filed:` prefix
