### ISSUE TITLE
objectMapper.readValue does not work for classes which extends hashmap

### ISSUE THREAD

**Issue by oddaolse** [micronaut-projects/micronaut-serialization#739]
### Expected Behavior

Given : 
@io.micronaut.serde.annotation.Serdeable  
@Introspected  
public class Content extends HashMap<String, String> {  
  
}

Then 

final String someContent = """  
  {
	  "someKey": "someValue"
  }
 """;
 
.......    

List<Content> contentList = Arrays.asList(objectMapper.readValue(someContent, Argument.of(Content.class)));  
  
Content content = contentList.get(0);  
var someValue = content.get("someKey");  
assertEquals("someValue", someValue);

Should work.

### Actual Behaviour

Content becomes empty.

However : 
List contentList = Arrays.asList(objectMapper.readValue(someContent, Argument.mapOf(String.class, String.class)));  
  
HashMap<String, String> content = (HashMap<String, String>) contentList.get(0);  
var someValue = content.get("someKey");  
assertEquals("someValue", someValue);

Works.

Which does not help me a lot since Content may be an attribute in another class.

### Steps To Reproduce

1. Download example application from GitHub
2. ./gradlew test

### Environment Information

JDK : 17
OS : MacOS

### Example Application

https://github.com/oddaolse/serdedemo

### Version

4

**Comment by oddaolse** [comment]
It is a rather annoying error. If I have not explained it - please give instructions on how to submit this which seams like a bug.

**Comment by dstepanov** [comment]
How do you expect it to work? Does it work with Jackson?
The best would be to write a custom deserializer.

**Comment by oddaolse** [comment]
Hi. I expect it to work as described in "Expected behaviour". Let me know if it is unclear. The link to github contains a small project which shows what fails.
Yes. It works with Jackson.
I am implementing a custom deserializer as a workaround. The deserialize works. However - since I  have "implements Serde<Content>" I have to implement both deserialize and serialize. And the serialize part I am struggeling with.

**Comment by oddaolse** [comment]
I implemented workaround - custom deserializer. I will close this, even if I still consider it as a bug.
