### ISSUE TITLE
Could you please provide an update on when the next release is planned?

### ISSUE THREAD

**Issue by ramilS** [micronaut-projects/micronaut-serialization#776]
### Issue description

I'm waiting some fixes

**Comment by sdelamo** [comment]
see: https://github.com/micronaut-projects/micronaut-core/discussions/10527

https://micronaut.io/micronaut-roadmap/

**Comment by dstepanov** [comment]
We can probably release a minor version already, but you will need to reference it directly.

**Comment by ramilS** [comment]
@dstepanov it'll be great thank you
