### ISSUE TITLE
Cannot find serialize/deserializer ... Multiple possible serializers found for type [Map ...]: []

### ISSUE THREAD

**Issue by meriouma** [micronaut-projects/micronaut-serialization#817]
### Expected Behavior

I believe this is again related to #761. Before v2.8.2, it was working fine. I have two custom serializers marked as `@Secondary` for specific use cases of `Map<String, Any?>` that I use with `@Serdeable.Serializable(using = MyCustomSerde::class)`.

### Actual Behaviour

With v2.8.2+, for any field of type Map not flagged with `@Serdeable.Serializable(using = MyCustomSerde::class)`, I get the message
```
Cannot find serialize/deserializer for type: class ....Organization. Error resolving serializer for property [BeanProperty{beanType=class ....Organization, type=interface java.util.Map, name='name'}] of type [java.util.Map]: Multiple possible serializers found for type [Map name]: []
```

It seems as though the default beans serdes cannot be found anymore.

### Environment Information

- JDK 17

### Version

4.3.8

**Comment by dstepanov** [comment]
You can annotate your serde as `@Bean(typed = MyCustomSerde.class)` This will eliminate it from the shared onces

**Comment by meriouma** [comment]
@dstepanov Thanks, that seems to do the trick.
