### ISSUE TITLE
Error while serializing objects created with @SerdeImport

### ISSUE THREAD

**Issue by spyroid** [micronaut-projects/micronaut-serialization#837]
### Expected Behavior

http://localhost:8080/p1 - should return a Product class in JSON format 
http://localhost:8080/p2 - should return a Product2 record in JSON format 

### Actual Behaviour

http://localhost:8080/p1 throws an error java.lang.NoSuchMethodError: 'double com.example.Product.getPrice()'
http://localhost:8080/p2 returns an empty JSON object

### Environment Information

JDK 17,21

### Example Application

https://github.com/spyroid/demoapp

### Version

4.4.2

**Comment by sdelamo** [comment]
It is a ksp issue. I created a fork of your repo. I added a test and it passes when using KAPT https://github.com/spyroid/demoapp/pull/1

**Comment by spyroid** [comment]
> It is a ksp issue. I created a fork of your repo. I added a test and it passes when using KAPT [spyroid/demoapp#1](https://github.com/spyroid/demoapp/pull/1)

Thanks. Do I need to raise an issue ticket for KSP ?

**Comment by sdelamo** [comment]
> > It is a ksp issue. I created a fork of your repo. I added a test and it passes when using KAPT [spyroid/demoapp#1](https://github.com/spyroid/demoapp/pull/1)
> 
> Thanks. Do I need to raise an issue ticket for KSP ?

No, this issue suffices.
