### ISSUE TITLE
@JsonCreator being ignored on internal enums

### ISSUE THREAD

**Issue by KazimirDobrzhinsky** [micronaut-projects/micronaut-serialization#882]
### Expected Behavior

`@JsonCreator` annotation shall be used, if you use it on the enum, which is internal for the class

### Steps To Reproduce

When the enum is inside of the other class and fromValue method is marked as '@JsonCreator', this static fromValue method is ignored and the valueOf() enum method is used instead 

### Environment Information

Java 21
Micronaut parent 4.5.0

### Version

4.5.0

**Comment by dstepanov** [comment]
Please create a sample app. Make sure the enum is annotated with `@Serdeable`

**Comment by KazimirDobrzhinsky** [comment]
That was a problem and I am extremely sorry for this ticket. I used Serdeable only on the outer class and therefore it didn't work.
